#!/usr/bin/env bash
# Generate .github/dependabot.yml from the Dockerfiles in the repository.
# Run from the repository root:  ./scripts/generate-dependabot.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT="${REPO_ROOT}/.github/dependabot.yml"

cat > "$OUTPUT" << 'HEADER'
# Auto-generated by scripts/generate-dependabot.sh – do not edit manually.
version: 2

updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions
HEADER

# Find every Dockerfile, extract the directory relative to repo root,
# and emit a dependabot entry for each one.
find "$REPO_ROOT" -mindepth 3 -maxdepth 3 -name Dockerfile \
    -not -path '*/.github/*' -printf '%P\n' | \
  sed 's|/Dockerfile$||' | sort -t/ -k1,1 -k2,2V | while read -r dir; do
    tool="${dir%%/*}"
    cat >> "$OUTPUT" << EOF

  # ${tool}
  - package-ecosystem: docker
    directory: /${dir}
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker
EOF
done

echo "Generated ${OUTPUT} with $(grep -c 'package-ecosystem: docker' "$OUTPUT") Docker entries."
